package vn.topica.sf18.constant;

public enum UserAction {
  USER_LOGIN,

  ADMIN_ASSIGN_ROLE,

  MARKETER_IMPORT_FILE,
  MARKETER_CHANGE_IMPORTED_FILE,
  MARKETER_UPDATE_CAMPAIGN_DETAIL,

  MANAGER_CONFIRM_IMPORTED_FILE,
  MANAGER_RUN_MAPPING_DATA,
  MANAGER_SYNC_OLD_DATA,
}
