package vn.topica.sf18.constant;

public enum UserAction {
  USER_LOGIN,

  ADMIN_ASSIGN_ROLE,

  MARKETER_IMPORT_FILE,
  MARKETER_CHANGE_IMPORTED_FILE,
  MARKETER_UPDATE_CAMPAIGN_DETAIL,

  MANAGER_CONFIRM_IMPORTED_FILE,
  MANAGER_RUN_MAPPING_DATA,
  MANAGER_SYNC_OLD_DATA,

  USER_FILTER_CAMPAIGN,
  USER_FILTER_IMPORT_FILE,
  USER_FILTER_LOG,
  USER_FIND_BY_ID_CAMPAIGN,
  USER_FIND_BY_ID_IMPORT_FILE,
  USER_FIND_BY_ID_LOG,
}
